Repository Gosrock/Ticket-Backend, pull requests merged in 2022-01, with the labels that each got.

#14 🚀 어드민 회원가입,로그인 ,인증미들웨어 , 티켓발급, 내티켓 확인 작업
  src/index.js
  src/middleware/AdminAuthentication.js
  src/middleware/index.js
  src/middleware/validationCatch.js
  src/model/Ticket.js
  src/model/index.js
  src/routes/RouteAdminRegister.js
  src/routes/RouteAdminlogin.js
  src/routes/RouteGetTickets.js
  src/routes/RoutePostTickets.js
  src/routes/RouteTest.js
  src/routes/index.js
  src/utils/jwtTokenGenerate.js
Labels: 기능추가, 찬진

#17 🚀 티켓 검색 및 리스트업 (페이지네이션 처리)API
  src/index.js
  src/routes/RouteTicketListUp.js
  src/routes/index.js
Labels: 기능추가, 민준

#18 :rocket #16
  src/routes/RouteTicketListUp.js
Labels: 버그, 민준

#23 공짜 티켓 발급 API 작성
  src/index.js
  src/routes/RoutePostAdminTickets.js
  src/routes/RouteTicketListUp.js
  src/routes/index.js
Labels: 기능추가, 민준
